spring:
    application:
        name: schema-registry-demo-service-xyz

    kafka:
        bootstrap-servers: 'pkc-41p56.asia-south1.gcp.confluent.cloud:9092'
        schema.registry.url: 'https://psrc-lzvd0.ap-southeast-2.aws.confluent.cloud'
        properties:
            bootstrap.servers: pkc-41p56.asia-south1.gcp.confluent.cloud:9092
            ssl.endpoint.identification.algorithm: https
            security.protocol: SASL_SSL
            sasl.mechanism: PLAIN
            sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="" password="";
            basic.auth.credentials.source: USER_INFO
            schema.registry.basic.auth.user.info: ''
            schema.registry.url: https://psrc-lzvd0.ap-southeast-2.aws.confluent.cloud

        consumer:
            bootstrap-servers: 'pkc-41p56.asia-south1.gcp.confluent.cloud:9092'
            group-id: group_id
            auto-offset-reset: earliest
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.KafkaAvroSerializer
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

server:
    port: 9001

kafkademo:
    inboundTopic: "send-payment"
    outboundTopic: "payment-sent"
